stages:
  - test
  - package
  - docker
  - deploy
  - sync

variables:
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}/springboot-ecommerce"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn test

package:
  stage: package
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

docker_build_push:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main

deploy_k8s:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - kubectl apply -f k8s/
    - kubectl rollout restart deployment/ecommerce-backend -n ecommerce
  only:
    - main
  when: manual

sync_to_github:
  stage: sync
  image: alpine:3.20
  script:
    - apk add --no-cache git openssh-client
    - git config user.email "your-email"
    - git config user.name "gitlab-user"
    - git remote add github "https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git"
    - git push github HEAD:main
  only:
    - main
  when: manual
